# Generated by Django 3.2.7 on 2021-10-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=30)),
                ('salary', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
