# Generated by Django 3.2.7 on 2021-10-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
