# Generated by Django 3.2.7 on 2021-10-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('role', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
